WG-Server (Shared flat server)
==============================
Lasse Sprengel <lasse.sprengel@pm.me>
v0.1

:toc:

== THIS PROJECT IS STILL WIP. USE AT OWN RISK.

This project will provide different functionality in a shared flat. The idea is to have a tablet as dashboard inside the shared space. This connects to the phones and other devices and allows you to manage tasks, etc.

== Usage

There will be three ways of running this application:

Using docker (Recommended):: Not implemented

Using the gitlab release::
Simply download the latest release from https://github.com/Xenira/wg-server/releases. Extract the archive and run `yarn start` or `npm start` from within the extracted folder.

Using the source::
Clone the repository. Then run `yarn install` or `npm install`. Now you can run the server using `yarn start` or `npm start`. You could also build it yourself using `yarn build` or `npm build`.

== Environments

PORT:: Sets the port the server binds to

== Components

There will be several submodules

=== Task Management
This handles tasks in your flat. Use this to create a cleaning plan and other things that need to be done by the members.
